source: https://github.com/ianblenke/docker-huginn.git
requisites:
  - libpq-dev
data_container:
  huggin_data:
    - /app/public/uploads
database:
  postgresql:
    - huggin
env:
  BUNDLE_WITHOUT: "development:test:selenium:mysql:sqlite"
  APP_SECRET_TOKEN: "whatever rake secret"
  DATABASE_ADAPTER=mysql2
  DATABASE_ENCODING=utf8
  DATABASE_RECONNECT=true
  DATABASE_NAME=huginn_development
  DATABASE_POOL=5
  DATABASE_USERNAME=root
  DATABASE_PASSWORD=""

#docker-opts:

files:
  content:
    /Procfile: |
        web: RAILS_ENV=${RACK_ENV:-production} rake db:migrate && bundle exec puma -t 5:5 -p ${PORT:-8080} -e ${RAILS_ENV}
    /config/database.yml: |
        production:
          url: <%= ENV['DATABASE_URL'] %>
  append:
    /Gemfile: |
        gem "pg", group: :postgres
        gem "rails_12factor", group: :production
        gem "puma", group: :production
  templates:
    /config/site.yml: "salt://roles/imgbuilder/extra/dokku-definitions/tracks/site.yml"
execute:
  - config: git config user.email "saltmaster@localhost" && git config user.name "Salt Master"
  - bundle: bundle install --without mysql:sqlite:test:development:selenium
  - commit: git add Procfile config/site.yml config/database.yml && git commit -a -m "modified by salt"
