source:
  url: https://github.com/sameersbn/docker-gitlab.git
volume:
  gitlab_data:
    - /home/git/data
    - /var/log/gitlab
database:
  postgresql: gitlab
  redis: true
ssl:
  certificate: selfsigned
  key: none
env:
  DB_TYPE: postgres
  DB_HOST: postgresql
  DB_NAME: gitlab
  REDIS_HOST: redis

#  GITLAB_TIMEZONE: "{{ salt['pillar.get']('timezone', 'UTC') }}"
#  REDMINE_URL: 

#docker-opts:
#files:
