source: https://github.com/opf/openproject.git
branch: stable

volume:
  openproject_data:
    - /uploads
database:
  postgresql: openproject
  memcache: true
ssl:
  certificate: selfsigned
  key:
env:
  BUNDLE_WITHOUT: "development:test:selenium:mysql:sqlite"
  BUNDLE_WITH: "production:postgres"
  attachments_storage_path: "/uploads"
  rails_cache_store: "memcache"
  cache_namespace: "openproject"

#docker-opts: '-h host.domain.com'

files:
  content:
    Procfile: |
        web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
        worker: bundle exec rake jobs:work
        backup: ./packaging/scripts/backup
        check: ./packaging/scripts/check
        seed: bundle exec rake db:seed
    config/database.yml: |
        production:
          url: <%= ENV['DATABASE_URL'] %>
  append:
    Gemfile: |
        gem "rails_12factor", group: :production
