source:
  url: https://github.com/opf/openproject.git
  rev: stable
volume:
  openproject_data:
    - /uploads
database:
  postgresql: openproject
  memcached: openproject
ssl:
  certificate: selfsigned
env:
  SECRET_TOKEN: "{{ salt['random.str_encode'](salt['random.get_str'](64), 'hex') }}"
  BUNDLE_WITHOUT: "development:test:selenium:mysql:sqlite"
  BUNDLE_WITH: "production:postgres"
  attachments_storage_path: "/uploads"
  rails_cache_store: "memcache"
  cache_namespace: "openproject"

files:
  content:
    Procfile: |
        web: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
        worker: bundle exec rake jobs:work
    config/database.yml: |
        production:
          url: <%= ENV['DATABASE_URL'] %>
    .buildpacks: |
        https://github.com/heroku/heroku-buildpack-nodejs.git#v70
        https://github.com/heroku/heroku-buildpack-ruby.git#v133
    Gemfile.plugins: |
        gem "openproject-backlogs", :git => "https://github.com/finnlabs/openproject-backlogs.git", :branch => 'stable'
        gem 'openproject-costs', :git => 'https://github.com/finnlabs/openproject-costs.git', :branch => 'stable'
        gem 'openproject-global_roles', :git => 'https://github.com/finnlabs/openproject-global_roles.git', :branch => 'stable'
        gem 'openproject-help_link', :git => 'https://github.com/finnlabs/openproject-help_link.git', :branch => 'stable'
        gem 'openproject-meeting', :git => 'https://github.com/finnlabs/openproject-meeting.git', :branch => 'stable'
        gem 'openproject-my_project_page', :git => 'https://github.com/finnlabs/openproject-my_project_page.git', :branch => 'stable'
        gem 'openproject-pdf_export', :git => 'https://github.com/finnlabs/openproject-pdf_export.git', :branch => 'stable'
        gem 'openproject-documents', :git => 'https://github.com/opf/openproject-documents.git', :branch => 'stable'
        gem 'reporting_engine', :git => 'https://github.com/finnlabs/reporting_engine.git', :branch => 'stable'
        gem 'openproject-translations', :git => 'https://github.com/opf/openproject-translations.git', :branch => 'stable'
        gem "openproject-webhooks", :git => 'https://github.com/finnlabs/openproject-webhooks.git', :branch => 'stable'
        gem "openproject-github_integration", :git => 'https://github.com/finnlabs/openproject-github_integration.git', :branch => 'stable'
  append:
    Gemfile: |
        gem "rails_12factor", group: :production
    .gitignore: |
        /*.bak
  comment:
    .gitignore: ^(/?config/database.yml)|(/?Gemfile.plugins)
    Gemfile: ^ *gem "mysql2"

pre_commit:
  - 'bundle install --without="development test selenium mysql sqlite"'

post_commit:
  - 'bundle exec rake db:migrate db:seed'
