source: https://github.com/TracksApp/tracks.git
volume:
  tracks_data:
    - /app/public/uploads
database:
  postgresql: tracks
ssl:
  certificate: selfsigned
  key:
env:
  BUNDLE_WITHOUT: "development:test:selenium:mysql:sqlite"
#docker-opts:

files:
  content:
    Procfile: |
        web: RAILS_ENV=${RACK_ENV:-production} rake db:migrate && bundle exec puma -t 5:5 -p ${PORT:-8080} -e ${RAILS_ENV}
    config/database.yml: |
        production:
          url: <%= ENV['DATABASE_URL'] %>
  append:
    Gemfile: |
        gem "pg", group: :postgres
        gem "rails_12factor", group: :production
        gem "puma", group: :production
  comment:
    .gitignore: ^(config/site.yml)|(config/database.yml)
  templates:
    config/site.yml: "salt://roles/imgbuilder/extra/dokku-definitions/tracks/site.yml"
