source: https://github.com/loomio/loomio.git
#branch: master

volume:
  loomio_data:
    - /uploads
database:
  postgresql: loomio
  memcache: true
ssl:
  certificate: selfsigned
  key:
env:
  RACK_ENV: production
  RAILS_ENV: production
  DEVISE_SECRET: `openssl rand -base64 48`
  SECRET_COOKIE_TOKEN: `openssl rand -base64 48`
  CANONICAL_HOST: loomio.omoikane.ep3.at
  TLD_LENGTH: 3

#docker-opts: '-h test.domain.com'

files:
  content:
    Procfile: |
        web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
        worker: bundle exec rake jobs:work
        backup: ./packaging/scripts/backup
        check: ./packaging/scripts/check
        seed: bundle exec rake db:seed
    config/database.yml: |
        production:
          url: <%= ENV['DATABASE_URL'] %>
  append:
    Gemfile: |
        gem "rails_12factor", group: :production
  templates:
    config/site.yml: "salt://roles/imgbuilder/extra/dokku-definitions/tracks/site.yml"
