source: https://github.com/wuxxin/owncloud.git
volume:
  owncloud_data:
    - /var/www/owncloud/apps
    - /var/www/owncloud/config
    - /var/www/owncloud/data
    - /var/cache/lighttpd/uploads
database:
  postgresql: owncloud
env:
  DB_TYPE: pgsql
  TIMEZONE: "{{ salt['pillar.get']('timezone', 'UTC') }}"
ssl:
  certificate: selfsigned

hostname: owncloud.omoikane.ep3.at

#docker-opts: '-h owncloud.omoikane.ep3.at'



