source:
  url: https://github.com/bretif/docker-seafile.git
volume:
  seafile_data:
    - /opt/seafile
database:
  mariadb: 
    - seafile
    - ccnet
    - seahub
ssl:
  certificate: selfsigned
hostname: seafile.omoikane.ep3.at
env:
  DOMAIN: seafile.omoikane.ep3.at
  NAME: seafile
  SEAFILE_IP: seafile.omoikane.ep3.at
  MYSQL_HOST: mariadb
  MYSQL_USER: seafile
  AUTO_CONF_DB: "false"
  SEAHUB_DB_NAME: seahub
  CCNET_DB_NAME: ccnet
  SEAFILE_DB_NAME: seafile
files:
  uncomment:
    Dockerfile: EXPOSE
  replace:
    Dockerfile:
      change_baseimage:
        pattern: |
            FROM[ \t]+sudokeys/baseimage
        repl: |
            FROM phusion/baseimage
  append:
    scripts/deploy-seafile.sh: |
        touch /opt/seafile/seahub_settings.py
        chown seafile:seafile /opt/seafile/seahub_settings.py

