source:
  url: https://github.com/bretif/docker-seafile.git
volume:
  seafile_data:
    - /opt/seafile
database:
  mariadb: 
    - seafile
    - ccnet
    - seahub
http:
  hostname: seafile.omoikane.ep3.at
  ssl:
    certificate: selfsigned
  proxy:
  - port: 8002
    match: path_beg
    pattern: /seafhttp
    target: /
  - port: 8000
    target: / 
env:
  ## DOKKU_ENABLE_HTTP_HOST=1
  ## DOKKU_ENABLE_HSTS=1
  ## PROXY_HTTP_8002: /seafhttp /
  ## PROXY_HTTP_8000: /
  VIRTUAL_HOST: seafile.omoikane.ep3.at
  DOMAIN: seafile.omoikane.ep3.at
  SEAFILE_IP: seafile.omoikane.ep3.at
  NAME: seafile
  MYSQL_HOST: mariadb
  MYSQL_USER: seafile
  AUTO_CONF_DB: "false"
  SEAHUB_DB_NAME: seahub
  CCNET_DB_NAME: ccnet
  SEAFILE_DB_NAME: seafile
files:
  uncomment:
    Dockerfile: EXPOSE
  replace:
    Dockerfile:
      change_baseimage:
        pattern: |
            FROM[ \t]+sudokeys/baseimage
        repl: |
            FROM phusion/baseimage
  append:
    scripts/deploy-seafile.sh: |
        touch /opt/seafile/seahub_settings.py
        chown seafile:seafile /opt/seafile/seahub_settings.py
        ln -s /opt/seafile/seafile-server-${SEAFILE_VERSION} /opt/seafile/seafile-server-latest
